language: go

go:
  - 1.4
  - tip

install:
  - go get -u -f -v ./...
  - go get -u -f -v golang.org/x/crypto/bcrypt
  - go get -u -f -v gopkg.in/boj/redistore.v1
  - go get -u -f -v github.com/smartystreets/assertions
  - go get -u -f -v github.com/smartystreets/goconvey
  - go get -u -f -v github.com/morpheusxaut/eveapi
